services:
  nginx:
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - php
    build:
      context: docker/nginx
      args:
        SERVER_VERSION: $SERVER_VERSION
    tty: true
    stdin_open: true
    env_file: .env
    working_dir: $PHP_USER_HOME_DIRECTORY
    volumes:
      - ./.env:$PHP_USER_HOME_DIRECTORY/.env
      - ./docker/nginx/templates:/etc/nginx/templates
      - ./public:$PHP_USER_PUBLIC_DIRECTORY
      - ./src:$PHP_USER_SRC_DIRECTORY
      - ./vendor:$PHP_USER_VENDOR_DIRECTORY
    ports:
      - $SERVER_PORT:80

  php:
    container_name: php
    restart: unless-stopped
    depends_on:
      - mariadb
    build:
      context: docker/php
      args:
        PHP_VERSION: $PHP_VERSION
        PHP_USER_NAME: $PHP_USER_NAME
        PHP_USER_IDENTIFIER: $PHP_USER_IDENTIFIER
        PHP_USER_SHELL: $PHP_USER_SHELL
        PHP_USER_HOME_DIRECTORY: $PHP_USER_HOME_DIRECTORY
    tty: true
    stdin_open: true
    env_file: .env
    working_dir: $PHP_USER_HOME_DIRECTORY
    user: php
    volumes:
      - ./.env:$PHP_USER_HOME_DIRECTORY/.env
      - ./src:$PHP_USER_SRC_DIRECTORY
      - ./public:$PHP_USER_PUBLIC_DIRECTORY
      - ./vendor:$PHP_USER_VENDOR_DIRECTORY

  migration:
    container_name: migration
    restart: no
    depends_on:
      - mariadb
    build:
      context: docker/php
      args:
        PHP_VERSION: $PHP_VERSION
        PHP_USER_NAME: $PHP_USER_NAME
        PHP_USER_IDENTIFIER: $PHP_USER_IDENTIFIER
        PHP_USER_SHELL: $PHP_USER_SHELL
        PHP_USER_HOME_DIRECTORY: $PHP_USER_HOME_DIRECTORY
    tty: true
    stdin_open: true
    env_file: .env
    working_dir: $PHP_USER_HOME_DIRECTORY
    user: php
    volumes:
      - ./db:$PHP_USER_HOME_DIRECTORY
    command: php migrations/run_migrations.php
    profiles:
      - migration

  mariadb:
    container_name: mariadb
    restart: unless-stopped
    build:
      context: docker/mariadb
      args:
        DATABASE_VERSION: $DATABASE_VERSION
    tty: true
    stdin_open: true
    user: root
    env_file: .env
    working_dir: /var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: $DATABASE_ROOT_PASSWORD
      MARIADB_USER: $DATABASE_USER
      MARIADB_PASSWORD: $DATABASE_PASSWORD
      MARIADB_DATABASE: $DATABASE_NAME
    volumes:
      - ./database:/var/lib/mysql
