/:
  controller: MainController
  action: home

/articles/{slug}:
  controller: ArticleController
  action: index

#login

/login:
  controller: AuthController
  action: index

/login/submit:
  controller: AuthController
  action: post

/logout:
  controller: AuthController
  action: logout

#register

/register:
  controller: RegisterController
  action: index

/register/submit:
  controller: RegisterController
  action: post

#forgot password

/forgot-password:
  controller: ForgotPasswordController
  action: index

/forgot-password/submit:
  controller: ForgotPasswordController
  action: submit

/forgot-password/success:
  controller: ForgotPasswordController
  action: success

#reset password

/reset-password/{token}:
  controller: ResetPasswordController
  action: index

/reset-password/{token}/submit:
  controller: ResetPasswordController
  action: submit

/reset-password/{token}/success:
  controller: ResetPasswordController
  action: success

#upload photo

/group/{groupId}/upload:
  controller: UploadController
  action: index

/group/{groupId}/upload/post:
  controller: UploadController
  action: post

/group/{groupId}/upload/success:
  controller: UploadController
  action: success

#view photos
/group/{groupId}/photos:
  controller: PhotoController
  action: index

#create & delete group
/group/create:
  controller: GroupController
  action: renderCreateGroupPage

/group/create/submit:
  controller: GroupController
  action: create

/group/create/success:
  controller: GroupController
  action: createSuccess

/group/{groupId}/delete:
  controller: GroupController
  action: delete

#leave group
/group/member/settings:
  controller: UserGroupController
  action: renderMemberSettings

#group settings
/group/{groupId}/settings:
  controller: GroupController
  action: settings

/group/{groupId}/settings/save:
  controller: GroupController
  action: settingsSave

/group/{groupId}/settings/success:
  controller: GroupController
  action: settingsSuccess

/group/delete/success:
  controller: GroupController
  action: deleteSuccess

#group members settings
/group/{groupId}/members:
  controller: UserGroupController
  action: index

/group/{groupId}/member/{memberId}/manage:
  controller: UserGroupController
  action: manageMember

/group/{groupId}/member/{memberId}/update-access:
  controller: UserGroupController
  action: updateAccess

/group/{groupId}/member/{memberId}/remove:
  controller: UserGroupController
  action: removeMember

#search & join group
/group/search/result:
  controller: GroupController
  action: searchGroup

/group/join:
  controller: UserGroupController
  action: joinGroup

/group/leave:
  controller: UserGroupController
  action: leaveGroup

#manage group join requests
/group/{groupId}/join-requests:
  controller: GroupJoinRequestController
  action: index

/group/{groupId}/join-requests/{requestId}/process:
  controller: GroupJoinRequestController
  action: processRequest

#add member to group
/group/{groupId}/invite-member:
  controller: InviteMemberController
  action: index

#search user to invite
/group/{groupId}/invite-member/search:
  controller: InviteMemberController
  action: searchUser

#send invite
/group/{groupId}/invite-member/{memberId}/send:
  controller: InviteMemberController
  action: sendInvitation

#see received invitations
/invitations:
  controller: InvitationController
  action: index

#respond invitation
/invitations/{invitationId}/respond:
  controller: InvitationController
  action: respondInvitation

#view group
/group/{groupId}:
  controller: GroupController
  action: index
