/:
  controller: MainController
  action: home

/articles/{slug}:
  controller: ArticleController
  action: index

#login

/login:
  controller: AuthController
  action: index

/login/submit:
  controller: AuthController
  action: post

/logout:
  controller: AuthController
  action: logout

#register

/register:
  controller: RegisterController
  action: index

/register/submit:
  controller: RegisterController
  action: post

#forgot password

/forgot-password:
  controller: ForgotPasswordController
  action: index

/forgot-password/submit:
  controller: ForgotPasswordController
  action: submit

/forgot-password/success:
  controller: ForgotPasswordController
  action: success

#reset password

/reset-password/{token}:
  controller: ResetPasswordController
  action: index

/reset-password/{token}/submit:
  controller: ResetPasswordController
  action: submit

/reset-password/{token}/success:
  controller: ResetPasswordController
  action: success

#upload photo

/group/{groupId}/upload:
  controller: UploadController
  action: index

/group/{groupId}/upload/post:
  controller: UploadController
  action: post

/group/{groupId}/upload/success:
  controller: UploadController
  action: success

#view photos
/group/{groupId}/photos:
  controller: PhotoController
  action: index

#group
/group/create:
  controller: GroupController
  action: renderCreateGroupPage

/group/create/submit:
  controller: GroupController
  action: create

/group/create/success:
  controller: GroupController
  action: createSuccess

/group/{groupId}/settings:
  controller: GroupController
  action: settings

/group/{groupId}/settings/save:
  controller: GroupController
  action: settingsSave

/group/{groupId}/settings/success:
  controller: GroupController
  action: settingsSuccess

/group/{groupId}/delete:
  controller: GroupController
  action: delete

/group/delete/success:
  controller: GroupController
  action: deleteSuccess

/group/{groupId}:
  controller: GroupController
  action: index
